const express = require('express')
const app = express()
const cors = require('cors')
app.use(express.json())
app.use(cors())
const database = require('./Models/connection')
const userroute = require('./Routes/user.route')
const adminroute = require('./Routes/admin.route')
database.connect()
app.use('/api/user', userroute)
app.use('/api/admin', adminroute)
app.listen(6000)
console.log("we on http://localhost:6000")
module.exports = app