const express = require('express')
const router = express.Router()
const usercontrol = require('../Controller/user.control')
const userauth = require('../Middleware/user.auth')
const upload = require('../Helpers/helper')
router.post('/add', upload.single('file'), usercontrol.addUser)
router.post('/check/:id', usercontrol.changestatus)
router.put('/update/image/:id', upload.single('update'), usercontrol.updateUserImage)
router.put('/update/inf/:id', usercontrol.updateUserInformation)
router.delete('/delete/:id', usercontrol.deleteUser)
router.get('/find/:id', userauth, usercontrol.findUser)
router.post('/login', usercontrol.login)
router.post('/addtocart', userauth, usercontrol.AddtoCart)
router.post('/deletefromcart', userauth, usercontrol.DeletefromCart)
router.post('/placeorder', userauth, usercontrol.PlaceOrder)
router.get('/showcart', usercontrol.ShowCart)
module.exports = router